// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/SystemMessage.proto

package com.momoc.multi.chat.room.common.proto;

public final class SystemMessage {
  private SystemMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface sessionBuildResponse_100OrBuilder extends
      // @@protoc_insertion_point(interface_extends:sessionBuildResponse_100)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string token = 1;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 1;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code sessionBuildResponse_100}
   */
  public static final class sessionBuildResponse_100 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sessionBuildResponse_100)
      sessionBuildResponse_100OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use sessionBuildResponse_100.newBuilder() to construct.
    private sessionBuildResponse_100(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private sessionBuildResponse_100() {
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new sessionBuildResponse_100();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_sessionBuildResponse_100_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_sessionBuildResponse_100_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100.class, com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100.Builder.class);
    }

    public static final int TOKEN_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object token_ = "";
    /**
     * <code>string token = 1;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 1;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100)) {
        return super.equals(obj);
      }
      com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 other = (com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100) obj;

      if (!getToken()
          .equals(other.getToken())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sessionBuildResponse_100}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sessionBuildResponse_100)
        com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_sessionBuildResponse_100_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_sessionBuildResponse_100_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100.class, com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100.Builder.class);
      }

      // Construct using com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        token_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_sessionBuildResponse_100_descriptor;
      }

      @java.lang.Override
      public com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 getDefaultInstanceForType() {
        return com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100.getDefaultInstance();
      }

      @java.lang.Override
      public com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 build() {
        com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 buildPartial() {
        com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 result = new com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.token_ = token_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100) {
          return mergeFrom((com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 other) {
        if (other == com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100.getDefaultInstance()) return this;
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                token_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 1;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        token_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        token_ = getDefaultInstance().getToken();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        token_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sessionBuildResponse_100)
    }

    // @@protoc_insertion_point(class_scope:sessionBuildResponse_100)
    private static final com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100();
    }

    public static com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<sessionBuildResponse_100>
        PARSER = new com.google.protobuf.AbstractParser<sessionBuildResponse_100>() {
      @java.lang.Override
      public sessionBuildResponse_100 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<sessionBuildResponse_100> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<sessionBuildResponse_100> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.momoc.multi.chat.room.common.proto.SystemMessage.sessionBuildResponse_100 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface heartPopMessage_200OrBuilder extends
      // @@protoc_insertion_point(interface_extends:heartPopMessage_200)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *心跳消息
   * </pre>
   *
   * Protobuf type {@code heartPopMessage_200}
   */
  public static final class heartPopMessage_200 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:heartPopMessage_200)
      heartPopMessage_200OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use heartPopMessage_200.newBuilder() to construct.
    private heartPopMessage_200(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private heartPopMessage_200() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new heartPopMessage_200();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_heartPopMessage_200_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_heartPopMessage_200_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200.class, com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200)) {
        return super.equals(obj);
      }
      com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 other = (com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *心跳消息
     * </pre>
     *
     * Protobuf type {@code heartPopMessage_200}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:heartPopMessage_200)
        com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_heartPopMessage_200_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_heartPopMessage_200_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200.class, com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200.Builder.class);
      }

      // Construct using com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_heartPopMessage_200_descriptor;
      }

      @java.lang.Override
      public com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 getDefaultInstanceForType() {
        return com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200.getDefaultInstance();
      }

      @java.lang.Override
      public com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 build() {
        com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 buildPartial() {
        com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 result = new com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200) {
          return mergeFrom((com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 other) {
        if (other == com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:heartPopMessage_200)
    }

    // @@protoc_insertion_point(class_scope:heartPopMessage_200)
    private static final com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200();
    }

    public static com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<heartPopMessage_200>
        PARSER = new com.google.protobuf.AbstractParser<heartPopMessage_200>() {
      @java.lang.Override
      public heartPopMessage_200 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<heartPopMessage_200> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<heartPopMessage_200> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.momoc.multi.chat.room.common.proto.SystemMessage.heartPopMessage_200 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserNotRegisterChannel_201OrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserNotRegisterChannel_201)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *用户未进行登录注册
   * </pre>
   *
   * Protobuf type {@code UserNotRegisterChannel_201}
   */
  public static final class UserNotRegisterChannel_201 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserNotRegisterChannel_201)
      UserNotRegisterChannel_201OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserNotRegisterChannel_201.newBuilder() to construct.
    private UserNotRegisterChannel_201(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserNotRegisterChannel_201() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserNotRegisterChannel_201();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_UserNotRegisterChannel_201_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_UserNotRegisterChannel_201_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201.class, com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201)) {
        return super.equals(obj);
      }
      com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 other = (com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *用户未进行登录注册
     * </pre>
     *
     * Protobuf type {@code UserNotRegisterChannel_201}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserNotRegisterChannel_201)
        com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_UserNotRegisterChannel_201_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_UserNotRegisterChannel_201_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201.class, com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201.Builder.class);
      }

      // Construct using com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.momoc.multi.chat.room.common.proto.SystemMessage.internal_static_UserNotRegisterChannel_201_descriptor;
      }

      @java.lang.Override
      public com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 getDefaultInstanceForType() {
        return com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201.getDefaultInstance();
      }

      @java.lang.Override
      public com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 build() {
        com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 buildPartial() {
        com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 result = new com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201) {
          return mergeFrom((com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 other) {
        if (other == com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserNotRegisterChannel_201)
    }

    // @@protoc_insertion_point(class_scope:UserNotRegisterChannel_201)
    private static final com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201();
    }

    public static com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserNotRegisterChannel_201>
        PARSER = new com.google.protobuf.AbstractParser<UserNotRegisterChannel_201>() {
      @java.lang.Override
      public UserNotRegisterChannel_201 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserNotRegisterChannel_201> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserNotRegisterChannel_201> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.momoc.multi.chat.room.common.proto.SystemMessage.UserNotRegisterChannel_201 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sessionBuildResponse_100_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sessionBuildResponse_100_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heartPopMessage_200_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heartPopMessage_200_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserNotRegisterChannel_201_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserNotRegisterChannel_201_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/main/resources/proto/SystemMessage" +
      ".proto\")\n\030sessionBuildResponse_100\022\r\n\005to" +
      "ken\030\001 \001(\t\"\025\n\023heartPopMessage_200\"\034\n\032User" +
      "NotRegisterChannel_201B(\n&com.momoc.mult" +
      "i.chat.room.common.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sessionBuildResponse_100_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sessionBuildResponse_100_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sessionBuildResponse_100_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_heartPopMessage_200_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_heartPopMessage_200_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heartPopMessage_200_descriptor,
        new java.lang.String[] { });
    internal_static_UserNotRegisterChannel_201_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserNotRegisterChannel_201_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserNotRegisterChannel_201_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
